In [1]:
import pandas as pd

## Data Cleaning Process for Dataset

#### Analyze the data before cleaning

In [2]:
# import the dataset 
df = pd.read_csv('customer_shopping_behavior.csv')

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
# see # of rows, columns, Dtypes, null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [5]:
# Look at the summary statistics of the dataset (numerical values unless you put include='all')
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [6]:
# check missing values

'''
We see col "Review Rating" has 37 NA values so:
1. Understanding why the data is missing
2. Evaluate how much is missing 
    If it's less than 5% & random = replace with median (for outliers)
    If it's between 5-30 = replace with median (for numeric) (mode/"unknown" for categorical)
    If it's greater than 30% = assess importance--consider dropping col 
'''

df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

#### Clean the Data

In [7]:
# fills the missing values in col "Review Rating" with the median by their category group
# .transform() is making sure the rows are not collapsed like Window function in SQL
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [8]:
# Check to see if the null have been replaced
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [9]:
# Column name manipulation 

# turn to lower case 
df.columns = df.columns.str.lower()

# add the _
df.columns = df.columns.str.replace(' ', '_')

# change purchase_amount_(usd) with purchase_amount
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [10]:
# create a col age_group 
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']

'''
 .qcut = automatically divides the data into equal-sized percentile buckets. 
q=4 means: from a range of 18-70 age-group: 
1. the first 25% will be in bucket 1
2. the second 25% will be in bucket 2 
3. the third 25% will be in bucket 3
4. the fourth 25% will be in bucket 4

Additionally:
.cut - allows you to choose the range so:
1. put the 18-35 in bucket 1
2. put the 35-45 in bucket 2
'''
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [11]:
df[['age', 'age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [12]:
'''
create col called purchase frequence days so we can create numeric
stats for the 'frequency_of_purchases' col instead of worrying about
the text it gave us in that col 
'''
# first create a dict for each frequency_of_purchases
frequency_mapping = {
    'Fortnightly': 14, 
    'Weekly': 7, 
    'Annually': 365,
    'Quarterly': 90, 
    'Bi-Weekly': 14,
    'Monthly': 30,
    'Every 3 Months': 90
}

# Then create a new col with the new data of the value that maps to each text 
df['frequency_of_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [14]:
df[['frequency_of_days', 'frequency_of_purchases']].head(10)

   frequency_of_days frequency_of_purchases
0                 14            Fortnightly
1                 14            Fortnightly
2                  7                 Weekly
3                  7                 Weekly
4                365               Annually
5                  7                 Weekly
6                 90              Quarterly
7                  7                 Weekly
8                365               Annually
9                 90              Quarterly

In [15]:
'''
Do we need both columns? If promo is used we can conclude a discount is applied
BUT it's possible automatic discount could be applied ex: during seasons
SO lets see if each of the rows match one another 
'''
df[['discount_applied', 'promo_code_used']]

     discount_applied promo_code_used
0                 Yes             Yes
1                 Yes             Yes
2                 Yes             Yes
3                 Yes             Yes
4                 Yes             Yes
...               ...             ...
3895               No              No
3896               No              No
3897               No              No
3898               No              No
3899               No              No

[3900 rows x 2 columns]

In [18]:
# .all() checkes if each row in 'discount_applied' matches 'promo_code_used'
# if so, return TRUE if not returns FALSE
(df['discount_applied'] == df['promo_code_used']).all()

True

In [19]:
# We don't need 'promo_code_used' if they match 
df.drop(columns='promo_code_used', inplace=True)

In [22]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,frequency_of_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

## DATA CLEANING DONE

In [25]:
pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.3.0-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Downloading pyodbc-5.3.0-cp312-cp312-win_amd64.whl (70 kB)
   ---------------------------------------- 0.0/70.1 kB ? eta -:--:--
   ---------------------------------------- 70.1/70.1 kB 1.9 MB/s eta 0:00:00
Installing collected packages: pyodbc
Successfully installed pyodbc-5.3.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [32]:
''' 
HOW TO IMPORT DF TO SQL SERVER
'''
import sqlalchemy as sa

# whats the server_name 
server = r"(localdb)\Local"
# whats the db name 
database = "Customer_Behaviour"

connection_string = (
    f"mssql+pyodbc://@{server}/{database}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
    "&trusted_connection=yes"
)

engine = sa.create_engine(connection_string)

# step 2: Import it into SQL Server 

# give it a table name 
table_name = 'customer'
# ship it to sql server 
df.to_sql(table_name, engine, if_exists='replace', index=False)

50